### ISSUE TITLE
VS code hello python master not working

### ISSUE THREAD

**Issue by sugarfree78** [ev3dev/ev3dev#1272]
**What are you trying to do?**
I am trying run hello python master code through bluetooth on my EV3 brick. the status of the device is on line in Visual studio code compiler but the code is not running on brick. 

**What did you expect to happen**
the code should work through blue-tooth connection

**What actually happened**
the print code displays the message in the terminal not on ev3 screen or outB  large motor is not connected

The program did..
gives error that outB large motor is not connected

**Source Code**

```python
#!/usr/bin/env python3
from ev3dev2.motor import MoveSteering, OUTPUT_B,OUTPUT_C

steer_pair = MoveSteering(OUTPUT_B, OUTPUT_C)
num_rots = 50/13.6
steer_pair.on_for_rotations(steering=0, speed=40, rotations=num_rots)
```

```
Traceback (most recent call last):
  File "c:/Users/Lenovo/Documents/ev3 projects/vscode-hello-python-master/hello.py", line 4, in <module>
    steer_pair = MoveSteering(OUTPUT_B, OUTPUT_C)
  File "c:\Users\Lenovo\Documents\ev3 projects\.venv\lib\site-packages\ev3dev2\motor.py", line 1791, in __init__
    MotorSet.__init__(self, motor_specs, desc)
  File "c:\Users\Lenovo\Documents\ev3 projects\.venv\lib\site-packages\ev3dev2\motor.py", line 1621, in __init__
    self.motors[motor_port] = motor_class(motor_port)
  File "c:\Users\Lenovo\Documents\ev3 projects\.venv\lib\site-packages\ev3dev2\motor.py", line 1088, in __init__
    super(LargeMotor, self).__init__(address, name_pattern, name_exact, driver_name=['lego-ev3-l-motor', 'lego-nxt-motor'], **kwargs)
  File "c:\Users\Lenovo\Documents\ev3 projects\.venv\lib\site-packages\ev3dev2\motor.py", line 366, in __init__
    super(Motor, self).__init__(self.SYSTEM_CLASS_NAME, name_pattern, name_exact, **kwargs)
  File "c:\Users\Lenovo\Documents\ev3 projects\.venv\lib\site-packages\ev3dev2\__init__.py", line 210, in __init__
    chain_exception(DeviceNotFound("%s is not connected." % self), None)
  File "c:\Users\Lenovo\Documents\ev3 projects\.venv\lib\site-packages\ev3dev2\__init__.py", line 38, in chain_exception
    raise exception from cause
ev3dev2.DeviceNotFound: LargeMotor(outB) is not connected.
```

**Desktop (please complete the following information):**
 - OS and version: Window 10
 - Connection Type: Bluetooth
 - Software: Visual Studio Code

**Robot (please complete the following information):**
 - Device: EV3
 - Versions: ev3dev-stretch-ev3-generic-2018-11-13

`

**Background Information**
I am working on self driving EV3 mind storm. during training samples collection, it takes image through IP webcam saves the image as numpy array along with the command on that specific picture in .txt file. it will train neural net work using that data and after that it will go in self drive mode. in self drive it suppose to communicate to EV3 through bluetooth to give commands.

**Comment by dlech** [comment]
1. Please update to the most recent version of ev3dev
2. Is there actually a large motor connected to port B? (No loose wires?)

**Comment by sugarfree78** [comment]
No, no loose wires. I actually realized that I need to send commands directly to ev3 but unable to do so.  can you help me in this regard. this is my first time working with ev3. thank you

**Comment by sugarfree78** [comment]
No, no loose wires. I actually realized that I need to send commands directly to ev3 but unable to do so. can you help me in this regard. this is my first time working with ev3. thank you
