### ISSUE TITLE
How can I create a connection to a sensor?

### ISSUE THREAD

**Issue by Krysek** [ev3dev/ev3dev#1364]
**Question**
How can I create a connection to a sensor (C/C++), e.g. infrared sensor or touch sensor?

**Background Information**
I'd like to create a connection to a sensor to read it out, but it seems, that I'm not able to develop this.

A connection to one or more motors is possible without any problems. I can also control these motors.

**My Approach**
Following sensor are connected to my PiStorms:
 - BAS1: Infrared sensor (EV3)
 - BAS2: Touch sensor (EV3)

*1st attempt: Sensor connection via C++ (infrared sensor)*
Here my C++ code:
```
int main() {
    cout << "Start" << "\r" << endl;
    
    infrared_sensor is1;
    if (!is1.connected()) {
        cout << "is1: no infrared sensor found!" << "\r" << endl;
        //return 1;
    } else {
        cout << "is1: connected!" << "\r" << endl;
    }
    
    
    infrared_sensor is2(INPUT_1);
    if (!is2.connected()) {
        cout << "is2: no infrared sensor found!" << "\r" << endl;
        //return 1;
    } else {
        cout << "is2: connected!" << "\r" << endl;
    }
    
    cout << "End" << endl;
    return 0;
}
```

Output:
My C++ code couldn't establish a sensor connection.
```
Start
is1: no infrared sensor found!
is2: no infrared sensor found!
End
```

*2nd attempt: Sensor connection via Python (touch sensor)*
I also tried to set up a connection via Python:
```
from ev3dev2.motor import LargeMotor, OUTPUT_A, OUTPUT_B, SpeedPercent, MoveTank
from ev3dev2.sensor import INPUT_1
from ev3dev2.sensor.lego import TouchSensor
from ev3dev2.led import Leds

ts = TouchSensor()
leds = Leds()

print("Press the touch sensor to change the LED color!")

while True:
    if ts.is_pressed:
        leds.set_color("LEFT", "GREEN")
        leds.set_color("RIGHT", "GREEN")
    else:
        leds.set_color("LEFT", "RED")
        leds.set_color("RIGHT", "RED")
```

Output:
My Python code couldn't establish a sensor connection.
```
$ sudo ./test.py
Traceback (most recent call last):
  File "./test.py", line 11, in <module>
    ts = TouchSensor()
  File "/usr/lib/python3/dist-packages/ev3dev2/sensor/lego.py", line 49, in __init__
    super(TouchSensor, self).__init__(address, name_pattern, name_exact, driver_name=['lego-ev3-touch', 'lego-nxt-touch'], **kwargs)
  File "/usr/lib/python3/dist-packages/ev3dev2/sensor/__init__.py", line 94, in __init__
    super(Sensor, self).__init__(self.SYSTEM_CLASS_NAME, name_pattern, name_exact, **kwargs)
  File "/usr/lib/python3/dist-packages/ev3dev2/__init__.py", line 210, in __init__
    chain_exception(DeviceNotFound("%s is not connected." % self), None)
  File "/usr/lib/python3/dist-packages/ev3dev2/__init__.py", line 38, in chain_exception
    raise exception from cause
ev3dev2.DeviceNotFound: TouchSensor is not connected.
```

*3rd attempt: Checking Brickman information*
According to my Brickman, there is no sensor connected:
![Brickman - Information on sensors](https://user-images.githubusercontent.com/16275671/71546959-4e62f800-299b-11ea-921e-c7a16db69200.jpg)

According to my Brickman, there is also no details for port BAS1 available:
![Brickman - Information on ports](https://user-images.githubusercontent.com/16275671/71546972-5de24100-299b-11ea-9d33-cb161e8b243c.jpg)

**Robot:**
 - Device: PiStorms V2

```
Image file:         ev3dev-stretch-rpi2-generic-2019-10-23
Kernel version:     4.14.114-ev3dev-2.3.4-rpi2
Brickman:           0.10.2
BogoMIPS:           38.40
Bluetooth:          
Board:              board0
BOARD_INFO_HW_REV=A02082
BOARD_INFO_MODEL=Raspberry Pi 3 Model B Rev 1.2
BOARD_INFO_SERIAL_NUM=00000000d08d05cf
BOARD_INFO_TYPE=main
Board:              board1
BOARD_INFO_FW_VER=V2.08
BOARD_INFO_MODEL=PiStorms
BOARD_INFO_TYPE=aux
```

Have you got any hints what I have to do to establish a connection to a EV3 sensor?
Do I have to configure anything, at first?

Cheers,
Krysek

**Comment by dlech** [comment]
On PiStorms, the mode of the port has to be set first before using a sensor. Also see #1400
