### ISSUE TITLE
How to call a function from another file

### ISSUE THREAD

**Issue by Juoper** [ev3dev/ev3dev#1439]
- ev3dev-version: 4.14.117-ev3dev-2-3-5-ev3
- ev3dev-lang-python version: 1.2.0

I want to use a function from another py file but it doesn't work

here is my code:
my main.py:
```

#!/usr/bin/env pybricks-micropython

from SelectRound import piepen
from time import sleep
from pybricks.hubs import EV3Brick
from pybricks.ev3devices import (Motor)
from pybricks.parameters import (Port)
from pybricks.robotics import DriveBase

# Write your program here
# Initialize motor and timer

left_motor = Motor(Port.B)
right_motor = Motor(Port.C)

ev3 = EV3Brick()

robot = DriveBase(left_motor, right_motor, wheel_diameter= 55.5, axle_track=104)

test()

```

Here is my test.py file:

```
#!/usr/bin/env pybricks-micropython
from main import ev3
from main import robot

def test():
    robot.straight(100)
    ev3.speaker.beep(100, 1000)
```

Error log:

Traceback (most recent call last):
  File "/home/robot/test/main.py", line 3, in <module>
  File "/home/robot/test/test.py", line 4, in <module>
  File "/home/robot/test/main.py", line 3, in <module>
ImportError: cannot import name test

**Comment by dlech** [comment]
FYI, the support site for Pybricks is https://github.com/pybricks/support.

The errors sound like you have a circular dependency - test is trying to import from main and main is trying to import from test. This is not allowed in Python. (The line 3 in the main.py that you have given is `from SelectRound import piepen`. The errors you have reported don't really match up with the code.)

To fix it, could pass `ev3` and `robot` as parameters to the `test()` function instead of importing them.
