### ISSUE TITLE
ev3 detects plugged-in nxt-i2c sensor on port but does not recognize it as a sensor (HiTechnic NXT Infrared Seeker MS1042)

### ISSUE THREAD

**Issue by MichaelBonnet** [ev3dev/ev3dev#1520]
**What are you trying to do?**

I am trying to somehow connect the old version of the [HiTechnic NXT Infrared Seeker, part number MS1042](https://brickipedia.fandom.com/wiki/MS1042_Infrared_Seeker). I have been able to find vanishingly little information on this module.

**What did you expect to happen**

I expected the ev3 to at least notice that there is a device connected to the port.

**What actually happened**

The brick does not detect anything plugged into the port I have plugged the IR seeker into.

On the ev3 brick itself, Device Browser -> Sensors reveals just one sensor connected (a LEGO Ultrasonic Sensor), when the IR seeker is fully and securely plugged in. 

Error when running the code below:

```
Starting: brickrun --directory="/home/robot/Project_3" "/home/robot/Project_3/main.py"
----------
Traceback (most recent call last):
  File "/home/robot/Project_3/main.py", line 21, in <module>
    ir = Sensor(INPUT_2, driver_name='ht-nxt-ir-seek-v2')
  File "/usr/lib/python3/dist-packages/ev3dev2/sensor/__init__.py", line 78, in __init__
    super(Sensor, self).__init__(self.SYSTEM_CLASS_NAME, name_pattern, name_exact, **kwargs)
  File "/usr/lib/python3/dist-packages/ev3dev2/__init__.py", line 223, in __init__
    chain_exception(DeviceNotFound("%s is not connected." % self), None)
  File "/usr/lib/python3/dist-packages/ev3dev2/__init__.py", line 54, in chain_exception
    raise exception from cause
ev3dev2.DeviceNotFound: Sensor(ev3-ports:in2) is not connected.
----------
Exited with error code 1.
```

**Source Code**

Here is the program I am trying to run.

```
#!/usr/bin/env python3

###############
### IMPORTS ###
###############

from ev3dev2.sensor import Sensor
from ev3dev2.motor import LargeMotor, OUTPUT_A, OUTPUT_B, SpeedPercent, MoveTank, MoveSteering
from ev3dev2.sensor import INPUT_1, INPUT_2, INPUT_3, INPUT_4, Sensor
from ev3dev2.sensor.lego import UltrasonicSensor
from ev3dev2.led import Leds

#############################
### SENSOR/ACTUATOR SETUP ###
#############################

steer_pair = MoveSteering(OUTPUT_A, OUTPUT_B)
tank_pair = MoveTank(OUTPUT_A, OUTPUT_B)

# Ultrasonic sensor setup
us = UltrasonicSensor(INPUT_1)
us.MODE_US_DIST_CM = 'US_DIST_CM'

# Infrared seeker setup
ir = Sensor(INPUT_2, driver_name='ht-nxt-ir-seek-v2')
ir.mode = 'DC'
```

Variations of 'ht-nxt-ir-seek-v2' such as v1, removing the v2, seek -> seeker, do nothing for me. Fundamentally, it is failing to recognize the device as connected. I'm not sure where to go from here.

**Screenshots**

N/A

**Desktop:**
 - OS and version: macOS X Big Sur 11.6
 - Connection Type: USB
 - Software: Visual Studio Code

**Robot (please complete the following information):**
 - Device: EV3
 - Versions: [see below - SD card image version, Linux kernel version, etc.]

**System info (from `ev3dev-sysinfo`)**
```
Image file:         ev3dev-stretch-ev3-generic-2020-04-10
Kernel version:     4.14.117-ev3dev-2.3.5-ev3
Brickman:           0.10.3
BogoMIPS:           148.88
Bluetooth:          
Board:              board0
BOARD_INFO_HW_REV=7
BOARD_INFO_MODEL=LEGO MINDSTORMS EV3
BOARD_INFO_ROM_REV=6
BOARD_INFO_SERIAL_NUM=00165355464C
BOARD_INFO_TYPE=main
```

**Background Information**

I am trying to use the IR seeker to detect the direction of an infrared emitter relative to the heading of a robot that also uses an ultrasonic sensor to detect the distance to objects. Together, these sensors give me the direction and distance information I need to make my ev3 act like a [Braitenburg vehicle](https://en.wikipedia.org/wiki/Braitenberg_vehicle). 

Edit: Changed title to better reflect what I believe to be the issue

How do I make the ev3 detect my plugged-in HiTechnic NXT Infrared Seeker (old version, not V2) (part # MS1042)? -> ev3 detects plugged-in nxt-i2c sensor on port but does not recognize it as a sensor (HiTechnic NXT Infrared Seeker MS1042)

**Comment by MichaelBonnet** [comment]
To clarify - in the Device Browser on the brick itself, Sensors shows just the ultrasonic sensor plugged into port 1 - `lego-ev3-us at ev3-ports:in1`.

Under Ports > ev3-ports:in2 actually shows  status of `nxt-i2c`, which tells me it is seeing that something is plugged in, but is not recognizing it as a sensor.

Edit: this issue seems similar to #1433, but for i2c rather than UART.

**Comment by MichaelBonnet** [comment]
More information gained: In previous projects using this module, the device name (in a CPP program) was `NXT_IR_SEEKER`. Perhaps there's a way to get a driver for it?

**Comment by dlech** [comment]
It doesn't look like there is a kernel driver for this, so you can build your own kernel and add a driver or you can just use raw I2C commands to communicate with the sensor.

**Comment by MichaelBonnet** [comment]
Writing a driver probably isn't in my wheelhouse, both skill-wise and time constraint-wise, so I've begun attempting to use the raw i2c:

```
# Infrared Seeker setup
from smbus import SMBus

# Open i2c bus 4 (plugged in on Port 2) and read one byte from address 0x01, offset 0
bus = SMBus(4)
while True:
    print("Reading ...", file=stderr)
    for i in range(0, 10):
        b = bus.read_byte_data(0x01, i)
        print(b, file=stderr)
    print("End of read", file=stderr)

bus.close()
```
The issue is that I get the same readings, no matter what area my emitter is in (using a TV remote with a button held down or a 940nm infrared LED):

```
Reading ...
253
86
49
46
50
32
32
32
72
105
End of read
Reading ...
253
86
49
46
50
32
32
32
72
105
End of read
```
This should, in theory, behave like the NXT Infrared Seeker v2, but I'm not sure how to extract that behavior/information, or if I'm even pulling the right information/translating the extracted information into the format I would expect.

**Comment by dlech** [comment]
Do you have documentation on the I2C registers of the sensor? Usually the values of interest start at register 0x42.

And I think you can use `read_i2c_block_data()` to read multiple bytes at a time, IIRC. Tip: use `struct.unpack()` to decode the bytes read.

**Comment by MichaelBonnet** [comment]
I've only been able to find documentation [on the V2 version](https://www.robotshop.com/media/files/pdf/introduction-nsk1042.pdf). I had been hoping that the usage would be similar, but to no avail after thumbing through quite a few addresses:

```
# Infrared Seeker setup
from smbus import SMBus
import struct

# Open i2c bus 4 (seeker is plugged into port 2) and read bytes
bus = SMBus(4)
# while True:
print("Reading ...", file=stderr)
for i in range(0, 0xFF):
    try:
        # b = bus.read_byte_data( (0x41 + i), 0)
        b = bus.read_i2c_block_data( (0x00 + i), 0)
        # b = struct.pack('<l', b)
        # b_prime = struct.unpack('<l', b)
        # b_prime = struct.unpack('<l', ''.join([chr(i) for i in b[:4]]))[0]
        print("Address "+str(hex(0x00+i))+" is good", file=stderr)
        print(b, file=stderr)
        # print(b_prime, file=stderr)
    except IOError:
        print("Address "+str(hex(0x00+i))+" not good", file=stderr)
print("End of read", file=stderr)

bus.close()
```

As you can see, I tried to use the `struct.unpack()` method you mentioned, but I couldn't quite figure it out.

```
Starting: brickrun --directory="/home/robot/Project_3" "/home/robot/Project_3/main.py"
----------
Reading ...
Address 0x0 not good
Address 0x1 is good
[253, 86, 49, 46, 50, 32, 32, 32, 72, 105, 84, 101, 99, 104, 110, 99, 73, 82, 32, 68, 105, 114, 46, 32, 0, 0, 0, 0, 0, 0, 0, 0]
Address 0x2 not good
Address 0x3 not good
Address 0x4 not good
Address 0x5 not good
Address 0x6 not good
Address 0x7 not good
Address 0x8 not good
Address 0x9 not good
Address 0xa not good
Address 0xb not good
Address 0xc not good
Address 0xd not good
Address 0xe not good
Address 0xf not good
Address 0x10 not good
Address 0x11 not good
Address 0x12 not good
Address 0x13 not good
Address 0x14 not good
Address 0x15 not good
Address 0x16 not good
Address 0x17 not good
Address 0x18 not good
Address 0x19 not good
Address 0x1a not good
Address 0x1b not good
Address 0x1c not good
Address 0x1d not good
Address 0x1e not good
Address 0x1f not good
Address 0x20 not good
Address 0x21 not good
Address 0x22 not good
Address 0x23 not good
Address 0x24 not good
Address 0x25 not good
Address 0x26 not good
Address 0x27 not good
Address 0x28 not good
Address 0x29 not good
Address 0x2a not good
Address 0x2b not good
Address 0x2c not good
Address 0x2d not good
Address 0x2e not good
Address 0x2f not good
Address 0x30 not good
Address 0x31 not good
Address 0x32 not good
Address 0x33 not good
Address 0x34 not good
Address 0x35 not good
Address 0x36 not good
Address 0x37 not good
Address 0x38 not good
Address 0x39 not good
Address 0x3a not good
Address 0x3b not good
Address 0x3c not good
Address 0x3d not good
Address 0x3e not good
Address 0x3f not good
Address 0x40 not good
Address 0x41 not good
Address 0x42 not good
Address 0x43 not good
Address 0x44 not good
Address 0x45 not good
Address 0x46 not good
Address 0x47 not good
Address 0x48 not good
Address 0x49 not good
Address 0x4a not good
Address 0x4b not good
Address 0x4c not good
Address 0x4d not good
Address 0x4e not good
Address 0x4f not good
Address 0x50 not good
Address 0x51 not good
Address 0x52 not good
Address 0x53 not good
Address 0x54 not good
Address 0x55 not good
Address 0x56 not good
Address 0x57 not good
Address 0x58 not good
Address 0x59 not good
Address 0x5a not good
Address 0x5b not good
Address 0x5c not good
Address 0x5d not good
Address 0x5e not good
Address 0x5f not good
Address 0x60 not good
Address 0x61 not good
Address 0x62 not good
Address 0x63 not good
Address 0x64 not good
Address 0x65 not good
Address 0x66 not good
Address 0x67 not good
Address 0x68 not good
Address 0x69 not good
Address 0x6a not good
Address 0x6b not good
Address 0x6c not good
Address 0x6d not good
Address 0x6e not good
Address 0x6f not good
Address 0x70 not good
Address 0x71 not good
Address 0x72 not good
Address 0x73 not good
Address 0x74 not good
Address 0x75 not good
Address 0x76 not good
Address 0x77 not good
Address 0x78 not good
Address 0x79 not good
Address 0x7a not good
Address 0x7b not good
Address 0x7c not good
Address 0x7d not good
Address 0x7e not good
Address 0x7f not good
Address 0x80 not good
Address 0x81 not good
Address 0x82 not good
Address 0x83 not good
Address 0x84 not good
Address 0x85 not good
Address 0x86 not good
Address 0x87 not good
Address 0x88 not good
Address 0x89 not good
Address 0x8a not good
Address 0x8b not good
Address 0x8c not good
Address 0x8d not good
Address 0x8e not good
Address 0x8f not good
Address 0x90 not good
Address 0x91 not good
Address 0x92 not good
Address 0x93 not good
Address 0x94 not good
Address 0x95 not good
Address 0x96 not good
Address 0x97 not good
Address 0x98 not good
Address 0x99 not good
Address 0x9a not good
Address 0x9b not good
Address 0x9c not good
Address 0x9d not good
Address 0x9e not good
Address 0x9f not good
Address 0xa0 not good
Address 0xa1 not good
Address 0xa2 not good
Address 0xa3 not good
Address 0xa4 not good
Address 0xa5 not good
Address 0xa6 not good
Address 0xa7 not good
Address 0xa8 not good
Address 0xa9 not good
Address 0xaa not good
Address 0xab not good
Address 0xac not good
Address 0xad not good
Address 0xae not good
Address 0xaf not good
Address 0xb0 not good
Address 0xb1 not good
Address 0xb2 not good
Address 0xb3 not good
Address 0xb4 not good
Address 0xb5 not good
Address 0xb6 not good
Address 0xb7 not good
Address 0xb8 not good
Address 0xb9 not good
Address 0xba not good
Address 0xbb not good
Address 0xbc not good
Address 0xbd not good
Address 0xbe not good
Address 0xbf not good
Address 0xc0 not good
Address 0xc1 not good
Address 0xc2 not good
Address 0xc3 not good
Address 0xc4 not good
Address 0xc5 not good
Address 0xc6 not good
Address 0xc7 not good
Address 0xc8 not good
Address 0xc9 not good
Address 0xca not good
Address 0xcb not good
Address 0xcc not good
Address 0xcd not good
Address 0xce not good
Address 0xcf not good
Address 0xd0 not good
Address 0xd1 not good
Address 0xd2 not good
Address 0xd3 not good
Address 0xd4 not good
Address 0xd5 not good
Address 0xd6 not good
Address 0xd7 not good
Address 0xd8 not good
Address 0xd9 not good
Address 0xda not good
Address 0xdb not good
Address 0xdc not good
Address 0xdd not good
Address 0xde not good
Address 0xdf not good
Address 0xe0 not good
Address 0xe1 not good
Address 0xe2 not good
Address 0xe3 not good
Address 0xe4 not good
Address 0xe5 not good
Address 0xe6 not good
Address 0xe7 not good
Address 0xe8 not good
Address 0xe9 not good
Address 0xea not good
Address 0xeb not good
Address 0xec not good
Address 0xed not good
Address 0xee not good
Address 0xef not good
Address 0xf0 not good
Address 0xf1 not good
Address 0xf2 not good
Address 0xf3 not good
Address 0xf4 not good
Address 0xf5 not good
Address 0xf6 not good
Address 0xf7 not good
Address 0xf8 not good
Address 0xf9 not good
Address 0xfa not good
Address 0xfb not good
Address 0xfc not good
Address 0xfd not good
Address 0xfe not good
End of read
----------
Completed successfully.

```
Only one register being readable at all seems ... fishy.

**Comment by dlech** [comment]
It looks like `read_i2c_block_data(address, register, length)` is missing the first parameter, 0x01, the I2C address of the sensor. And the length is 0, so it won't read any data. (for reading one byte at a time, just stick with `read_byte_data()`).

**Comment by MichaelBonnet** [comment]
We managed to figure it out. We finally managed to find a project that told us what drivers to use - specifically, these two files([1](https://github.com/botbench/rdpartyrobotcdr/blob/master/drivers/hitechnic-irseeker-v1.h), [2](https://github.com/botbench/rdpartyrobotcdr/blob/master/hitechnic-irseeker-v1-test1.c)) told us what we needed to know.

Relevant, working code:

```
from time import time, sleep
from smbus import SMBus
from sys import stderr

# Infrared Seeker setup
# Open i2c bus 4 (use port # + 2 -- seeker is plugged into port 2)
bus = SMBus(4)

# Takes the direction reading (0-9) from the IR seeker
# via direct, raw i2c interactions
# and returns it.
def get_ir_direction(bus):
    direction = bus.read_byte_data( 0x01, 0x42 )
    return direction

while True:
    # Sensor Reading Testing
    print( get_ir_direction(bus), file=stderr ) # prints to stderr so that we can see the readings on the computer screen rather than ev3 screen.
```

Thank you @dlech for pointing us in the right direction!

If anyone in the future wants to see what we're actually doing with it, see our [Autonomous Robots class project repo](https://github.com/MichaelBonnet/CSE4360-Projects).
