### ISSUE TITLE
Problems installing RPyC.

### ISSUE THREAD

**Issue by Robbe-Meersman** [ev3dev/ev3dev#1531]
So I was following [this tutorial](https://ev3dev-lang.readthedocs.io/projects/python-ev3dev/en/ev3dev-jessie/rpyc.html) and I kept getting the same error code. The RPyC server on the EV3 starts normally but as soon as I start the test program on my PC that was included in the tutorial I get the error messages. I'm now using the latest version of ev3dev namely 2020-04-10.

On the EV3(this is in an SSH window with the EV3): 

```
INFO:SLAVE/18812:server started on [0.0.0.0]:18812
INFO:SLAVE/18812:accepted 192.168.0.179:57095
INFO:SLAVE/18812:welcome [192.168.0.179]:57095
DEBUG:SLAVE/18812:Exception caught
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/lib/python3/dist-packages/rpyc/core/protocol.py", line 539, in _handle_inspect
    return tuple(netref.inspect_methods(self._local_objects[oid]))
  File "/usr/lib/python3/dist-packages/rpyc/lib/colls.py", line 86, in __getitem__
    return self._dict[key][0]
KeyError: ('3048453712', 'SlaveService', 'rpyc.core.service')
INFO:SLAVE/18812:goodbye [192.168.0.179]:57095
ERROR:SLAVE/18812:client connection terminated abruptly
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rpyc/utils/server.py", line 172, in _authenticate_and_serve_client
    self._serve_client(sock2, credentials)
  File "/usr/lib/python3/dist-packages/rpyc/utils/server.py", line 197, in _serve_client
    conn._init_service()
  File "/usr/lib/python3/dist-packages/rpyc/core/protocol.py", line 154, in _init_service
    self._local_root.on_connect()
  File "/usr/lib/python3/dist-packages/rpyc/core/service.py", line 145, in on_connect
    self._conn.modules = ModuleNamespace(self._conn.root.getmodule)
  File "/usr/lib/python3/dist-packages/rpyc/core/protocol.py", line 467, in root
    self._remote_root = self.sync_request(consts.HANDLE_GETROOT)
  File "/usr/lib/python3/dist-packages/rpyc/core/protocol.py", line 438, in sync_request
    self.serve(0.1)
  File "/usr/lib/python3/dist-packages/rpyc/core/protocol.py", line 390, in serve
    self._dispatch(data)
  File "/usr/lib/python3/dist-packages/rpyc/core/protocol.py", line 360, in _dispatch
    self._dispatch_reply(seq, args)
  File "/usr/lib/python3/dist-packages/rpyc/core/protocol.py", line 321, in _dispatch_reply
    obj = self._unbox(raw)
  File "/usr/lib/python3/dist-packages/rpyc/core/protocol.py", line 281, in _unbox
    proxy = self._netref_factory(oid, clsname, modname)
  File "/usr/lib/python3/dist-packages/rpyc/core/protocol.py", line 293, in _netref_factory
    info = self.sync_request(consts.HANDLE_INSPECT, oid)
  File "/usr/lib/python3/dist-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
_get_exception_class.<locals>.Derived: 'rpyc.core.service.ClassicService'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "C:\Users\robbe\AppData\Local\Programs\Python\Python310\lib\site-packages\rpyc\core\protocol.py", line 324, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "C:\Users\robbe\AppData\Local\Programs\Python\Python310\lib\site-packages\rpyc\core\protocol.py", line 599, in _handle_inspect
    if hasattr(self._local_objects[id_pack], '____conn__'):
  File "C:\Users\robbe\AppData\Local\Programs\Python\Python310\lib\site-packages\rpyc\lib\colls.py", line 110, in __getitem__
    return self._dict[key][0]
KeyError: 'rpyc.core.service.ClassicService'

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/rpyc/utils/server.py", line 172, in _authenticate_and_serve_client
    self._serve_client(sock2, credentials)
  File "/usr/lib/python3/dist-packages/rpyc/utils/server.py", line 197, in _serve_client
    conn._init_service()
  File "/usr/lib/python3/dist-packages/rpyc/core/protocol.py", line 154, in _init_service
    self._local_root.on_connect()
  File "/usr/lib/python3/dist-packages/rpyc/core/service.py", line 145, in on_connect
    self._conn.modules = ModuleNamespace(self._conn.root.getmodule)
  File "/usr/lib/python3/dist-packages/rpyc/core/protocol.py", line 467, in root
    self._remote_root = self.sync_request(consts.HANDLE_GETROOT)
  File "/usr/lib/python3/dist-packages/rpyc/core/protocol.py", line 438, in sync_request
    self.serve(0.1)
  File "/usr/lib/python3/dist-packages/rpyc/core/protocol.py", line 390, in serve
    self._dispatch(data)
  File "/usr/lib/python3/dist-packages/rpyc/core/protocol.py", line 360, in _dispatch
    self._dispatch_reply(seq, args)
  File "/usr/lib/python3/dist-packages/rpyc/core/protocol.py", line 321, in _dispatch_reply
    obj = self._unbox(raw)
  File "/usr/lib/python3/dist-packages/rpyc/core/protocol.py", line 281, in _unbox
    proxy = self._netref_factory(oid, clsname, modname)
  File "/usr/lib/python3/dist-packages/rpyc/core/protocol.py", line 293, in _netref_factory
    info = self.sync_request(consts.HANDLE_INSPECT, oid)
  File "/usr/lib/python3/dist-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
_get_exception_class.<locals>.Derived: 'rpyc.core.service.ClassicService'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "C:\Users\robbe\AppData\Local\Programs\Python\Python310\lib\site-packages\rpyc\core\protocol.py", line 324, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "C:\Users\robbe\AppData\Local\Programs\Python\Python310\lib\site-packages\rpyc\core\protocol.py", line 599, in _handle_inspect
    if hasattr(self._local_objects[id_pack], '____conn__'):
  File "C:\Users\robbe\AppData\Local\Programs\Python\Python310\lib\site-packages\rpyc\lib\colls.py", line 110, in __getitem__
    return self._dict[key][0]
KeyError: 'rpyc.core.service.ClassicService'

```

Error on the PC:
```
Exception has occurred: _get_exception_class.<locals>.Derived
('3048453712', 'SlaveService', 'rpyc.core.service')

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/lib/python3/dist-packages/rpyc/core/protocol.py", line 539, in _handle_inspect
    return tuple(netref.inspect_methods(self._local_objects[oid]))
  File "/usr/lib/python3/dist-packages/rpyc/lib/colls.py", line 86, in __getitem__
    return self._dict[key][0]
KeyError: ('3048453712', 'SlaveService', 'rpyc.core.service')
  File "C:\Users\robbe\OneDrive\Bureaublad\test rpic\test.py", line 2, in <module>
    conn = rpyc.classic.connect('ev3dev') # host name or IP address of the EV3


```

After these error codes, I followed [another tutorial](https://ev3dev-lang.readthedocs.io/projects/python-ev3dev/en/ev3dev-stretch/rpyc.html#references) but it gave the same results. 

I know this problem has been mentioned before in another[ post](https://github.com/ev3dev/ev3dev/issues/1359) but it was never solved I wanted to know if any progress has been made.

**Comment by tendwong** [comment]
Find out what is the version of Python and RPYC you have on your EV3DEV. For mine, the Python version is 3.5.3 and RPYC is 3.3.0. To fix the problem, you have to install the same version of Python and same version of RPYC on your desktop.

Python 3.5.3
https://www.python.org/downloads/release/python-353/

If you are on Windows, type 'py -m pip list' to see what RPYC you have. To install version 3.3.0 of RPYC, type 'py -m pip install rpyc==3.3.0'
