### ISSUE TITLE
Cant use any motors because of error "TypeError: Can't convert 'LargeMotor' object to str implicitly"

### ISSUE THREAD

**Issue by ozzux** [ev3dev/ev3dev#1532]
**What are you trying to do?**

I am trying to use my ev3 large motors to move a robotic arm.

**What did you expect to happen**

The program should have used the motors in a correct manner and the arm should have moved.

**What actually happened**

I got the output 

"Traceback (most recent call last):
  File "/home/robot/ev3dev_Projects/ev33testttt.py", line 10, in <module>
    Waist = ev3dev2.auto.MoveTank(LargeMotor(OUTPUT_B),LargeMotor(OUTPUT_C))
  File "/usr/lib/python3/dist-packages/ev3dev2/motor.py", line 1873, in __init__
    MotorSet.__init__(self, motor_specs, desc)
  File "/usr/lib/python3/dist-packages/ev3dev2/motor.py", line 1655, in __init__
    self.motors[motor_port] = motor_class(motor_port)
  File "/usr/lib/python3/dist-packages/ev3dev2/motor.py", line 1118, in __init__
    **kwargs)
  File "/usr/lib/python3/dist-packages/ev3dev2/motor.py", line 395, in __init__
    super(Motor, self).__init__(self.SYSTEM_CLASS_NAME, name_pattern, name_exact, **kwargs)
  File "/usr/lib/python3/dist-packages/ev3dev2/__init__.py", line 216, in __init__
    name = next(list_device_names(classpath, name_pattern, **kwargs))
  File "/usr/lib/python3/dist-packages/ev3dev2/__init__.py", line 137, in list_device_names
    if all([matches(path + '/' + k, kwargs[k]) for k in kwargs]):
  File "/usr/lib/python3/dist-packages/ev3dev2/__init__.py", line 137, in <listcomp>
    if all([matches(path + '/' + k, kwargs[k]) for k in kwargs]):
  File "/usr/lib/python3/dist-packages/ev3dev2/__init__.py", line 132, in matches
    return value.find(pattern) >= 0
TypeError: Can't convert 'LargeMotor' object to str implicitly
----------
Exited with error code 1.
"

**Source Code**

Here is the program I am trying to run.

```
#!/usr/bin/env python3

from ev3dev2.motor import *
import ev3dev2.auto
import ev3dev2.sound

spkr = ev3dev2.sound.Sound()

elbow = LargeMotor(OUTPUT_D)
Waist = ev3dev2.auto.MoveTank(LargeMotor(OUTPUT_B),LargeMotor(OUTPUT_C))

Waist.on_for_seconds(10,10,3)

```

**Desktop (please complete the following information):**
 - Windows 11 22000.613
 - Connection Type: Wifi
 - Software: Visual Studio

**Robot (please complete the following information):**
 - EV3
 - Versions: [see below - SD card image version, Linux kernel version, etc.]

```
Image file:         ev3dev-stretch-ev3-generic-2020-04-10
Kernel version:     4.14.117-ev3dev-2.3.5-ev3
Brickman:           0.10.3
BogoMIPS:           148.88
Bluetooth:          
Board:              board0
BOARD_INFO_HW_REV=7
BOARD_INFO_MODEL=LEGO MINDSTORMS EV3
BOARD_INFO_ROM_REV=6
BOARD_INFO_SERIAL_NUM=0016534E886A
BOARD_INFO_TYPE=main
```

**Comment by ozzux** [comment]
Forgot to mention that it was working fine yesterday, but today it's not.

**Comment by ozzux** [comment]
Figured it out, you don't include the LargeMotor part in the moveTank function.
