### ISSUE TITLE
NXT TouchSensor not detected on EV3

### ISSUE THREAD

**Issue by jenny1research** [ev3dev/ev3dev#1595]
**What are you trying to do?**

I have been using MicroPython on Visual Studio Code to program Lego Mindstorms EV3. 

I am trying to write a program to detect my touch sensor. While my brick is EV3, the touch sensor is from the NXT kit.

**What did you expect to happen**

For the EV3 brick to detect the NXT TouchSensor.

**What actually happened**

The error I get is: 
Starting: brickrun --directory="/home/robot/my_project" "/home/robot/my_project/main.py"

Traceback (most recent call last):
  File "/home/robot/my_project/main.py", line 23, in <module>
OSError: [Errno 19] ENODEV: 

A sensor or motor is not connected to the specified port:
--> Check the cables to each motor and sensor.
--> Check the port settings in your script.
--> Check the line in your script that matches
    the line number given in the 'Traceback' above.

----------
Exited with error code 1.

**Source Code**

Here is the program I am trying to run.

```
#!/usr/bin/env pybricks-micropython
from pybricks.hubs import EV3Brick
from pybricks.ev3devices import (Motor, TouchSensor, ColorSensor,
                                 InfraredSensor, UltrasonicSensor, GyroSensor)
from pybricks.parameters import Port, Stop, Direction, Button, Color
from pybricks.tools import wait, StopWatch, DataLog
from pybricks.robotics import DriveBase
from pybricks.media.ev3dev import SoundFile, ImageFile

# Create your objects here. 

ev3 = EV3Brick() 
left_wheel = Motor(Port.B)  
right_wheel = Motor(Port.C)  
robot = DriveBase(left_wheel,right_wheel,wheel_diameter=56,axle_track=100)  
touch = TouchSensor(Port.S1) 

# Write your program here. 

while True: 
if touch.pressed() == True: 
robot.turn(100) 

```

**Screenshots**

**Desktop (please complete the following information):**
 - OS and version: macOS 10.13.6
 - Connection Type: USB
 - Software: Visual Studio Code

**Robot (please complete the following information):**
 - Device: EV3
 - Versions: SD card

**Comment by dlech** [comment]
To use an NXT touch sensor, you need to use `from pybricks.nxtdevices import TouchSensor` instead of `from pybricks.ev3devices import TouchSensor`. If you need both , you can do this:

```python
from pybricks.ev3devices import TouchSensor as EV3TouchSensor
from pybricks.nxtdevices import TouchSensor as NXTTouchSensor
```

**Comment by jenny1research** [comment]
> To use an NXT touch sensor, you need to use `from nxtdevices import TouchSensor` instead of `from ev3devices import TouchSensor`. If you need both , you can do this:
> 
> ```python
> from ev3devices import TouchSensor as EV3TouchSensor
> from nxtdevices import TouchSensor as NXTTouchSensor
> ```


Thank you for your prompt response. 

I have revised my code as shown below, but I am still having issues. I removed the TouchSensor from the line "from ev3devices import ..." and instead included "from nxtdevices import TouchSensor".

Could you please let me know how else I should revise this?

```
#!/usr/bin/env pybricks-micropython
from pybricks.hubs import EV3Brick
from pybricks.ev3devices import (Motor, ColorSensor,
                                 InfraredSensor, UltrasonicSensor, GyroSensor)
from pybricks.parameters import Port, Stop, Direction, Button, Color
from pybricks.tools import wait, StopWatch, DataLog
from pybricks.robotics import DriveBase
from pybricks.media.ev3dev import SoundFile, ImageFile

from nxtdevices import TouchSensor

# This program requires LEGO EV3 MicroPython v2.0 or higher.
# Click "Open user guide" on the EV3 extension tab for more information.


# Create your objects here.
ev3 = EV3Brick()
left_wheel = Motor(Port.B) 
right_wheel = Motor(Port.C) 
robot = DriveBase(left_wheel,right_wheel,wheel_diameter=56,axle_track=100) 

touch = TouchSensor(Port.S1)

# Write your program here.

while True: 
    if touch.pressed() == True: 
        robot.turn(100)

```

This is the error message that I am getting:

Starting: brickrun --directory="/home/robot/my_project" "/home/robot/my_project/main.py"

Traceback (most recent call last):
  File "/home/robot/my_project/main.py", line 10, in <module>
ImportError: no module named 'nxtdevices'

Exited with error code 1.

**Comment by dlech** [comment]
Oops, I missed adding `pybricks.` in my suggestions. It should be:

```python
from pybricks.nxtdevices import TouchSensor
```

**Comment by jenny1research** [comment]
Thank you for your help, the NXT TouchSensor is now being detected! Would the same modification apply to NXT sound sensor and NXT ultrasonic sensor?

```
from pybricks.nxtdevices import TouchSensor, SoundSensor, UltrasonicSensor
```

**Comment by dlech** [comment]
> Would the same modification apply to NXT sound sensor and NXT ultrasonic sensor?

Yes, it applies for all NXT sensors, so those and more, e.g. `ColorSensor`.

**Comment by jenny1research** [comment]
> ```python
> #!/usr/bin/env pybricks-micropython
> from pybricks.hubs import EV3Brick
> from pybricks.ev3devices import (Motor, ColorSensor,
>                                  InfraredSensor, UltrasonicSensor, GyroSensor)
> from pybricks.parameters import Port, Stop, Direction, Button, Color
> from pybricks.tools import wait, StopWatch, DataLog
> from pybricks.robotics import DriveBase
> from pybricks.media.ev3dev import SoundFile, ImageFile
> 
> from nxtdevices import TouchSensor
> 
> # This program requires LEGO EV3 MicroPython v2.0 or higher.
> # Click "Open user guide" on the EV3 extension tab for more information.
> 
> 
> # Create your objects here.
> ev3 = EV3Brick()
> left_wheel = Motor(Port.B) 
> right_wheel = Motor(Port.C) 
> robot = DriveBase(left_wheel,right_wheel,wheel_diameter=56,axle_track=100) 
> 
> touch = TouchSensor(Port.S1)
> 
> # Write your program here.
> 
> while True: 
>     if touch.pressed() == True: 
>         robot.turn(100)
> ```

Thank you for the clarification. It is much appreciated.

I am now trying to create a loop to react to the touch sensor. However, the below code makes the EV3 turn but it does not go straight when the touch sensor is pressed. When the first three lines of coding is written without the else statement, the touch sensor works as intended. Could you let me know which part should be modified?

```
# Write your program here.
while True: 
    if touch.pressed() == True: 
        robot.straight(100)
    else:
        robot.turn(10000)
```

**Comment by dlech** [comment]
It depends on what the desired behavior of the robot is. But I'm guessing you want something like this:

```python
# Write your program here.

speed, _, turn_rate, _ = robot.settings()

while True: 
    if touch.pressed(): 
        robot.straight(100)
    else:
        robot.drive(speed, turn_rate)
        wait(10)
```

`DriveBase.drive()` is not a blocking function, so it doesn't take any time. It just starts motors or updates the speed if already running then the program continues immediately. `robot.turn(10000)` is a very long running function and will block the rest of the program from running until it completes.

On EV3, it is also important to always have some sort of delay in long running loop like to allow time for the Linux OS to keep running in the background. In this case, I have added a `wait()` for this.

**Comment by jenny1research** [comment]
> ```python
> # Write your program here.
> 
> speed, _, turn_rate, _ = robot.settings()
> 
> while True: 
>     if touch.pressed() == True: 
>         robot.straight(100)
>     else:
>         robot.drive(speed, turn_rate)
>         wait(10)
> ```

Thank you for all your help. 

With the above program, the robot goes straight when the touch sensor is pressed, but it does not move otherwise. 

I am now hoping to program the robot to go straight when the touch sensor is not pressed, and have the robot turn when the touch sensor is pressed. Would this be possible?

**Comment by dlech** [comment]
I would `print(speed, turn_rate)` to see what the values are. Maybe speed is 0 which is why it isn't moving?

To rephrase the desired behavior, it sounds like you want the robot to go straight until the the touch sensor is pressed, then turn, then repeat.

So this could be written as:

```python

while True:
    # start driving straight and continue with the program
    robot.drive(500, 0)

    # wait until touch sensor is pressed
    while not touch.pressed():
        wait(10)

    # turn 90 degrees
    robot.turn(90)

    # then loop back and start driving straight again
```

**Comment by jenny1research** [comment]
> I would `print(speed, turn_rate)` to see what the values are. Maybe speed is 0 which is why it isn't moving?
> 
> To rephrase the desired behavior, it sounds like you want the robot to go straight until the the touch sensor is pressed, then turn, then repeat.
> 
> So this could be written as:
> 
> ```python
> while True:
>     # start driving straight and continue with the program
>     robot.drive(500, 0)
> 
>     # wait until touch sensor is pressed
>     while not touch.pressed():
>         wait(10)
> 
>     # turn 90 degrees
>     robot.turn(90)
> 
>     # then loop back and start driving straight again
> ```

Thank you for your help. I unfortunately am still having issues. 

I got the error message below and tried unplugging the sensor and motor and plugged it back in again, but the issue still persists. I believe it is not an issue with the EV3 brick as I am able to run other programs that have been downloaded to EV3 by manually accessing the file browser. Could you let me know what steps I need to take to reboot the hub?

Thanks for all your help.

See below for the error message I am getting in my output:
```
Starting: brickrun --directory="/home/robot/my_project" "/home/robot/my_project/main.py"
----------
Traceback (most recent call last):
  File "/home/robot/my_project/main.py", line 18, in <module>
OSError: [Errno 5] EIO: 

Unexpected hardware input/output error with a motor or sensor:
--> Try unplugging the sensor or motor and plug it back in again.
--> To see which sensor or motor is causing the problem,
    check the line in your script that matches
    the line number given in the 'Traceback' above.
--> Try rebooting the hub/brick if the problem persists.


----------
Exited with error code 1.
```

**Comment by dlech** [comment]
What is line 18 in your program?

If it is a motor, you might try rotating it a little bit, then unplug it and plug it back in.

To reboot, just turn the EV3 off and turn it back on again.

**Comment by jenny1research** [comment]
> What is line 18 in your program?
> 
> To reboot, just turn the EV3 off and turn it back on again.

This is line 18 in my program:
left_wheel = Motor(Port.B) 

Thank you for your help. The error above is gone now. However, the program is still not behaving the way intended. As discussed above, I want the robot to go straight until the the touch sensor is pressed, then turn, then repeat. But when I run the program below, the robot does not move and when the touch sensor is pressed, it goes straight, instead of turning.

Could you let me know what I may be missing here?

Thanks for all your help.

```python
#!/usr/bin/env pybricks-micropython
from pybricks.hubs import EV3Brick
from pybricks.ev3devices import (Motor, ColorSensor,
                                 InfraredSensor, UltrasonicSensor, GyroSensor)
from pybricks.parameters import Port, Stop, Direction, Button, Color
from pybricks.tools import wait, StopWatch, DataLog
from pybricks.robotics import DriveBase
from pybricks.media.ev3dev import SoundFile, ImageFile

from pybricks.nxtdevices import TouchSensor

# This program requires LEGO EV3 MicroPython v2.0 or higher.
# Click "Open user guide" on the EV3 extension tab for more information.


# Create your objects here.
ev3 = EV3Brick()
left_wheel = Motor(Port.B) 
right_wheel = Motor(Port.C) 
robot = DriveBase(left_wheel,right_wheel,wheel_diameter=56,axle_track=100) 

touch = TouchSensor(Port.S1)

# Write your program here.

while True:
    # start driving straight and continue with the program
    robot.drive(500, 0)

    # wait until touch sensor is pressed
    while not touch.pressed():
        wait(10)

    # turn 90 degrees
    robot.turn(90)

    # then loop back and start driving straight again

```

**Comment by dlech** [comment]
Are you using medium or large motors? If you are using medium, then that would explain going straight instead of turning. To fix, you would need to change the positive direction on one of the motors.
