### ISSUE TITLE
Possible problem with Motors on PiStorms V1 + Raspberry Pi 1 Model B & 3 + Latest image

### ISSUE THREAD

**Issue by jabrena** [ev3dev/ev3dev#818]
### What did you do?

Testing Raspberry Pi 1 Model B and 3, I observed that the method to rotate and rotateTo doesn´t have the same behaviour than in BrickPi+ & EV3.

Besides, it is not possible with a Regulated motor to swith to an unregulated mode.

``` 
ev3dev#1|2017-01-15 16:12:56 [main] DEBUG ev3dev.utils.Sysfs - echo run-direct > /sys/class/tacho-motor/motor11/command
ev3dev#1|2017-01-15 16:12:56 [main] ERROR ev3dev.utils.Sysfs - Invalid argument
ev3dev#1|Exception in thread "main" java.lang.RuntimeException: Operation not executed: /sys/class/tacho-motor/motor11/command with value run-direct
ev3dev#1|	at ev3dev.hardware.EV3DevDevice.setStringAttribute(EV3DevDevice.java:122)
ev3dev#1|	at ev3dev.actuators.motors.BaseRegulatedMotor.forward(BaseRegulatedMotor.java:106)
ev3dev#1|	at examples.raspberrypi3.pistorms.motors.UnregulatedMotorDemo2.main(UnregulatedMotorDemo2.java:28)
Failed command ev3dev#1 with status 1: java -jar /home/robot/ev3dev-lang-java-all-0.4.0-SNAPSHOT.jar
``` 

Is it something known?

### What did you expect to happen?

This is the traces to observe that the developer try to rotate but the method state receive the same result and never finish the rotate process:

```
java -jar /home/robot/ev3dev-lang-java-all-0.4.0-SNAPSHOT.jar
ev3dev#1|2017-01-15 16:10:28 [main] DEBUG e.a.motors.BaseRegulatedMotor - Detecting motor on port: pistorms:BBM1
ev3dev#1|2017-01-15 16:10:28 [main] DEBUG ev3dev.hardware.EV3DevDevice - Detecting motors with port: pistorms:BBM1
ev3dev#1|2017-01-15 16:10:28 [main] DEBUG ev3dev.utils.Sysfs - ls /sys/class/lego-port
ev3dev#1|2017-01-15 16:10:29 [main] DEBUG ev3dev.utils.Sysfs - cat /sys/class/lego-port/port0/address
ev3dev#1|2017-01-15 16:10:29 [main] DEBUG ev3dev.utils.Sysfs - cat /sys/class/lego-port/port1/address
ev3dev#1|2017-01-15 16:10:29 [main] DEBUG ev3dev.utils.Sysfs - cat /sys/class/lego-port/port2/address
ev3dev#1|2017-01-15 16:10:29 [main] DEBUG ev3dev.hardware.EV3DevDevice - Detected port on path: /sys/class/lego-port/port2/address
ev3dev#1|2017-01-15 16:10:29 [main] DEBUG e.a.motors.BaseRegulatedMotor - Setting port in mode: tacho-motor
ev3dev#1|2017-01-15 16:10:29 [main] DEBUG ev3dev.utils.Sysfs - echo tacho-motor > /sys/class/lego-port/port2/mode
ev3dev#1|2017-01-15 16:10:29 [main] DEBUG lejos.utility.Delay - Delay: 500
ev3dev#1|2017-01-15 16:10:29 [main] DEBUG ev3dev.hardware.EV3DevDevice - Detecting motors with port: pistorms:BBM1
ev3dev#1|2017-01-15 16:10:29 [main] DEBUG ev3dev.utils.Sysfs - ls /sys/class/tacho-motor
ev3dev#1|2017-01-15 16:10:29 [main] DEBUG ev3dev.utils.Sysfs - cat /sys/class/tacho-motor/motor10/address
ev3dev#1|2017-01-15 16:10:29 [main] DEBUG ev3dev.hardware.EV3DevDevice - Detected port on path: /sys/class/tacho-motor/motor10/address
ev3dev#1|2017-01-15 16:10:29 [main] DEBUG ev3dev.utils.Sysfs - echo reset > /sys/class/tacho-motor/motor10/command
ev3dev#1|2017-01-15 16:10:29 [main] DEBUG ev3dev.utils.Sysfs - echo reset > /sys/class/tacho-motor/motor10/command
ev3dev#1|2017-01-15 16:10:29 [main] DEBUG ev3dev.utils.Sysfs - echo 100 > /sys/class/tacho-motor/motor10/speed_sp
ev3dev#1|2017-01-15 16:10:29 [main] DEBUG ev3dev.utils.Sysfs - echo hold > /sys/class/tacho-motor/motor10/stop_action
ev3dev#1|2017-01-15 16:10:29 [main] DEBUG ev3dev.utils.Sysfs - cat /sys/class/tacho-motor/motor10/position
ev3dev#1|2017-01-15 16:10:29 [main] INFO  e.r.p.m.RegulatedMotorRotateToDemo - 0
ev3dev#1|2017-01-15 16:10:29 [main] INFO  e.r.p.m.RegulatedMotorRotateToDemo - 90
ev3dev#1|2017-01-15 16:10:29 [main] DEBUG ev3dev.utils.Sysfs - echo 90 > /sys/class/tacho-motor/motor10/position_sp
ev3dev#1|2017-01-15 16:10:29 [main] DEBUG ev3dev.utils.Sysfs - echo run-to-abs-pos > /sys/class/tacho-motor/motor10/command
ev3dev#1|2017-01-15 16:10:29 [main] DEBUG ev3dev.utils.Sysfs - cat /sys/class/tacho-motor/motor10/state
ev3dev#1|2017-01-15 16:10:29 [main] DEBUG ev3dev.utils.Sysfs - cat /sys/class/tacho-motor/motor10/state
ev3dev#1|2017-01-15 16:10:29 [main] DEBUG ev3dev.utils.Sysfs - cat /sys/class/tacho-motor/motor10/state
ev3dev#1|2017-01-15 16:10:29 [main] DEBUG ev3dev.utils.Sysfs - cat /sys/class/tacho-motor/motor10/state
ev3dev#1|2017-01-15 16:10:29 [main] DEBUG ev3dev.utils.Sysfs - cat /sys/class/tacho-motor/motor10/state
ev3dev#1|2017-01-15 16:10:29 [main] DEBUG ev3dev.utils.Sysfs - cat /sys/class/tacho-motor/motor10/state
ev3dev#1|2017-01-15 16:10:29 [main] DEBUG ev3dev.utils.Sysfs - cat /sys/class/tacho-motor/motor10/state
```
 
The method rotate or rotateTo never finish

### What hardware and software are you using (including version numbers)?

**System info (from `ev3dev-sysinfo`)**
```
Image file:         ev3dev-jessie-rpi2-generic-2016-12-21
Kernel version:     4.4.32-17-ev3dev-rpi2
Board:              Raspberry Pi 3 Model B Rev 1.2
Revision:           a02082
Brickman:           0.8.1
ev3devKit:          0.4.3
```

**Comment by dlech** [comment]
> Besides, it is not possible with a Regulated motor to swith to an unregulated mode.

I don't think that PiStorms has an unregulated mode. The user manual says that it does (i.e. it says that you can use RCX motors), but I have not figured out how to make it work. If someone would like to play around with it and try to figure it out, be my guest. I would suggest opening an issue specifically for this feature if you want this to be looked into.

> The method rotate or rotateTo never finish

Can you please post a bash script that can be used to reproduce the problem? It is too much work for me to try to figure out what your java program is doing.

**Comment by jabrena** [comment]
Yes, tomorrow, I will send all data

**Comment by jabrena** [comment]
Hi @dlech, this is the summary from logs:

```
echo tacho-motor > /sys/class/lego-port/port2/mode
echo reset > /sys/class/tacho-motor/motor10/command
echo 100 > /sys/class/tacho-motor/motor10/speed_sp
echo hold > /sys/class/tacho-motor/motor10/stop_action
cat /sys/class/tacho-motor/motor10/position
echo 90 > /sys/class/tacho-motor/motor10/position_sp
echo run-to-abs-pos > /sys/class/tacho-motor/motor10/command
cat /sys/class/tacho-motor/motor10/state
```

I observed the same behaviour with Pi 1 & 3

This week, I will test PiStorms V2.

Cheers.

Juan Antonio

**Comment by dlech** [comment]
I performed the following and the motor worked as expected. The motor rotated 90 degrees and then stopped (well, it chatters a bit, but that is a mindsensors.com firmware bug - see #696).

```
root@ev3dev-rpi3:~# cd /sys/class/tacho-motor/motor2
root@ev3dev-rpi3:/sys/class/tacho-motor/motor2# cat address
pistorms:BAM1
root@ev3dev-rpi3:/sys/class/tacho-motor/motor2# echo 400 > speed_sp
root@ev3dev-rpi3:/sys/class/tacho-motor/motor2# echo hold > stop_action
root@ev3dev-rpi3:/sys/class/tacho-motor/motor2# cat position
-39
root@ev3dev-rpi3:/sys/class/tacho-motor/motor2# echo 90 > position_sp 
root@ev3dev-rpi3:/sys/class/tacho-motor/motor2# echo run-to-abs-pos > command
root@ev3dev-rpi3:/sys/class/tacho-motor/motor2# cat state
running
root@ev3dev-rpi3:/sys/class/tacho-motor/motor2#
```

There is no need to set the mode of output the port. It is already tacho-motor by default.

**Comment by jabrena** [comment]
Mmmm, so for Raspi 1, it is necessary to detect the version of Raspberry Pi to not execute the operation. Anyway to see the firmware installed on PiStorms V1 & V2?

Maybe if I have some Java Hasmap with all version could enough to detect the generation:

http://elinux.org/RPi_HardwareHistory#Raspberry_Pi_2_Model_B

```
/proc/cpuinfo | grep Revision
``` 

I will test this week.

In the test with all boards, I detected other problems. I will create a summary along this week.

Many Thanks @dlech 

Cheers

Juan Antonio

**Comment by dlech** [comment]
Is this still a problem?

**Comment by jabrena** [comment]
Hi @dlech, 

Many months ago, I only put the focus on Raspi3, but if you like, tomorrow, I will execute a test iteration with raspi 1. With Raspi3 and PiStorms V2, I have received some sensors issues. 

Take a look the following slides about my conclusions with previous image:

```
robot@ev3dev:~$ uname -r
4.4.68-20-ev3dev-ev3

robot@ev3dev:~$ uname -r
4.4.68-20-ev3dev-rpi2
```

http://ev3dev-lang-java.github.io/#/3/1
http://ev3dev-lang-java.github.io/#/3/2
http://ev3dev-lang-java.github.io/#/3/3

This weekend, I will inform about the status @dlech 

Juan Antonio

**Comment by jabrena** [comment]
**Note:** I continue using `Jessie` if you need to test `Stretch`, I could help in the testing process, but at the moment I only use Jessie. :)
